/* Copyright (C) 2013 David Li <li.davidm96@gmail.com>

   This file is part of Fiction Music.

   Fiction Music is free software: you can redistribute it and/or modify it
   under the terms of the GNU General Public License as published by the Free
   Software Foundation, either version 3 of the License, or (at your option)
   any later version.

   Fiction Music is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
   FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
   more details.

   You should have received a copy of the GNU General Public License along with
   Fiction Music.  If not, see <http://www.gnu.org/licenses/>. */


package com.lithiumli.fiction;

import android.app.Activity;
import android.app.ActionBar;
import android.app.Fragment;
import android.os.Bundle;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.TextView;
import android.util.Log;

import android.support.v4.view.PagerAdapter;
import android.support.v4.view.ViewPager;

public class NowPlayingActivity
    extends FictionActivity
{
    TextView mSongName;
    TextView mSongAlbum;
    TextView mSongArtist;
    ViewPager mCoverPager;
    CoverAdapter mAdapter;

    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.now_playing);

        mCoverPager = (ViewPager) findViewById(R.id.cover_pager);

        mAdapter = new CoverAdapter(this, mCoverPager);
        mCoverPager.setAdapter(mAdapter);
        mCoverPager.setCurrentItem(CoverAdapter.COVER_MIDDLE, false);

        // mCoverPager.setPageMargin(-50);
        // mCoverPager.setHorizontalFadingEdgeEnabled(true);
        // mCoverPager.setFadingEdgeLength(30);

        // set this afterwards so it doesn't try to handle the event
        // generated by setting the current item above
        mCoverPager.setOnPageChangeListener(mAdapter);

        mSongName = (TextView) findViewById(R.id.np_song_name);
        mSongAlbum = (TextView) findViewById(R.id.np_song_album);
        mSongArtist = (TextView) findViewById(R.id.np_song_artist);
        mSongArtist.setSelected(true);

        ActionBar ab = getActionBar();
        ab.setDisplayHomeAsUpEnabled(true);
        ab.setTitle("Now Playing");
        ab.setSubtitle("Fiction Music");
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
        case android.R.id.home:
            Intent parentIntent = new Intent(this, LibraryActivity.class);
            parentIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
            startActivity(parentIntent);
            finish();
            return true;
        }
        return super.onOptionsItemSelected(item);
    }

    @Override
    public void onSongChange(Song song) {
        mSongName.setText(song.getTitle());
        mSongAlbum.setText(song.getAlbum());
        mSongArtist.setText(song.getArtist());
    }

    // with thanks to
    // thehayro.blogspot.com/2012/12/enable-infinite-paging-with-android.html
    public class CoverAdapter
        extends PagerAdapter
        implements ViewPager.OnPageChangeListener {
        private static final int COVER_LEFT = 0;
        private static final int COVER_MIDDLE = 1;
        private static final int COVER_RIGHT = 2;

        FictionActivity mActivity;
        ViewPager mPager;
        int mSelectedCoverIndex;
        int mPrevCoverIndex;
        boolean mEvent = true;
        TextView[] mCovers = new TextView[3];

        public CoverAdapter(FictionActivity activity, ViewPager pager) {
            mActivity = activity;
            mPager = pager;
        }

        @Override
        public int getItemPosition(Object object) {
            return POSITION_NONE;
        }

        @Override
        public void destroyItem(ViewGroup container, int position, Object object) {
            container.removeView((View) object);
        }

        @Override
        public int getCount() {
            return 3;
        }

        @Override
        public TextView instantiateItem(ViewGroup container, int position) {
            int offset = -1;

            if (isAtBeginning()) {
                offset = 0;
                if (mEvent) {
                    setCurrentItemNoEvent(CoverAdapter.COVER_LEFT);
                }
            }
            else if (isAtEnd()) {
                offset = -2;
                if (mEvent) {
                    setCurrentItemNoEvent(CoverAdapter.COVER_RIGHT);
                }
            }

            TextView view = new TextView(mActivity);
            Song song = getSong(position + offset);
            view.setText(song.getAlbum() + song.getTitle());
            container.addView(view);
            mCovers[position] = view;
            return view;
        }

        @Override
        public boolean isViewFromObject(View view, Object obj) {
            return view == obj;
        }

        private Song getSong(int offset) {
            if (mActivity.isServiceBound()) {
                PlaybackQueue queue = mActivity.getService().getQueue();
                int position = queue.getCurrentPosition();

                if (position + offset < 0) {
                    Log.d("fiction", "too low");
                    return null;
                }
                if (position + offset > (queue.getCount() - 1)) {
                    Log.d("fiction", "too high");
                    return null;
                }

                return queue.getItem(position + offset);
            }
            return null;
        }

        private void setCover(int cover, Song song) {
            if (song == null)
                mCovers[cover].setText("BUG: no song!");
            mCovers[cover].setText(song.getAlbum() + song.getTitle());
        }

        public boolean isNearBeginning() {
            if (mActivity.isServiceBound()) {
                return
                    mActivity.getService().getQueue().getCurrentPosition() == 1;
            }
            return false;
        }

        public boolean isNearEnd() {
            if (mActivity.isServiceBound()) {
                PlaybackQueue queue = mActivity.getService().getQueue();
                return queue.getCurrentPosition() == (queue.getCount() - 2);
            }
            return false;
        }

        public boolean isAtBeginning() {
            if (mActivity.isServiceBound()) {
                return
                    mActivity.getService().getQueue().getCurrentPosition() == 0;
            }
            return false;
        }

        public boolean isAtEnd() {
            if (mActivity.isServiceBound()) {
                PlaybackQueue queue = mActivity.getService().getQueue();
                return queue.getCurrentPosition() == (queue.getCount() - 1);
            }
            return false;
        }

        public void setCurrentItemNoEvent(int position) {
            mEvent = false;
            mPager.setCurrentItem(position, false);
            mEvent = true;
        }

        @Override
        public void onPageSelected(int position) {
            mPrevCoverIndex = mSelectedCoverIndex;
            mSelectedCoverIndex = position;
        }

        @Override
        public void onPageScrollStateChanged(int state) {
            if (!mEvent) return;

            if (state == ViewPager.SCROLL_STATE_IDLE) {
                Song prevSong = getSong(-1);
                Song currentSong = getSong(0);
                Song nextSong = getSong(1);

                // swipe to right (left page)
                if (mSelectedCoverIndex < mPrevCoverIndex ||
                    mSelectedCoverIndex == COVER_LEFT) {
                    if (isNearBeginning()) {
                        setCover(COVER_LEFT, prevSong);
                        setCover(COVER_MIDDLE, currentSong);
                    }
                    else if (isAtBeginning()) {
                        return;
                    }
                    else {
                        setCover(COVER_RIGHT, getSong(-2));
                        setCover(COVER_MIDDLE, prevSong);
                        setCover(COVER_LEFT, currentSong);
                        mPager.setCurrentItem(COVER_MIDDLE, false);
                    }

                    if (mActivity.isServiceBound()) {
                        mActivity.getService().prev();
                    }
                }
                // swipe to left (right page)
                else if (mSelectedCoverIndex > mPrevCoverIndex ||
                         mSelectedCoverIndex == COVER_RIGHT) {
                    if (isNearEnd()) {
                        setCover(COVER_MIDDLE, currentSong);
                        setCover(COVER_RIGHT, nextSong);
                    }
                    else if (isAtEnd()) {
                        return;
                    }
                    else {
                        setCover(COVER_LEFT, currentSong);
                        setCover(COVER_MIDDLE, nextSong);
                        setCover(COVER_RIGHT, getSong(2));
                        mPager.setCurrentItem(COVER_MIDDLE, false);
                    }

                    if (mActivity.isServiceBound()) {
                        mActivity.getService().next();
                    }
                }
            }
        }

        @Override
        public void onPageScrolled(int position,
                                   float positionOffset,
                                   int positionOffsetPixels) {
        }
    }
}
